### ISSUE TITLE
Consider adding installation support via krew

### ISSUE THREAD

**Issue by jamesread** [predatorray/kubectl-alias#1]
I believe Krew is the de-facto standard for managing kubectl plugins now-a-days - that's what I use at least. https://krew.sigs.k8s.io/

**Comment by predatorray** [comment]
This is really a good idea! Let me submit a PR to the krew index.

**Comment by predatorray** [comment]
Krew is supported now. Please see the latest README.

P.S.: This plugin is available from a self-hosting index instead of the official one, because it is [against plugin lifecycle](https://github.com/kubernetes-sigs/krew-index/pull/2424).
