### ISSUE TITLE
Krew installation failed

### ISSUE THREAD

**Issue by ciiiii** [predatorray/kubectl-alias#6]
```bash
➜ krew install predatorray/alias
Updated the local copy of plugin index.
Updated the local copy of plugin index "predatorray".
plugin "predatorray/alias" does not exist in the plugin index
```
Looks like alias is not defined in https://github.com/predatorray/krew-index

**Comment by predatorray** [comment]
Thanks for reporting the issue, Yisheng.

The previous repository was deleted by mistake and is being used as a fork of the official krew repository. I just created a new custom index repo instead to host the `alias` plugin: [predatorray/my-krew-index](https://github.com/predatorray/my-krew-index). Please use the following command to install. The README will also be updated accordingly.

```sh
# Please note that there is `my-` prefix in the url.
kubectl krew index add predatorray https://github.com/predatorray/my-krew-index.git
kubectl krew install predatorray/alias
```

Sorry for the inconvenience. Please feel free to reopen this if the issue remains.
